version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: eventbooking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    depends_on:
      - postgres

  # app:
  #   build: .
  #   container_name: event-booking-app
  #   environment:
  #     DATABASE_HOST: postgres
  #     DATABASE_PORT: 5432
  #     DATABASE_USERNAME: yourusername
  #     DATABASE_PASSWORD: yourpassword
  #     DATABASE_NAME: eventbooking
  #     JWT_SECRET: your_jwt_secret
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
