version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: eventbooking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    depends_on:
      - postgres
    networks:
      - app-network

  app:
    build: .
    container_name: event-booking
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: yourusername
      DB_PASSWORD: yourpassword
      DB_NAME: eventbooking
      JWT_SECRET: your_jwt_secret
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
